const { Router } = require('express')

const authRoutes = require('./auth')
const productRoutes = require('./products')
const categoryRoutes = require('./categories')
const saleRoutes = require('./sales')
const userRoutes = require('./users')
const inventoryRoutes = require('./inventory')
const reportRoutes = require('./reports')
const supplierRoutes = require('./suppliers')
const auditRoutes = require('./audit')
const configRoutes = require('./config')
const permissionRoutes = require('./permissions')
const purchaseOrderRoutes = require('./purchaseOrders')
const expenseRoutes = require('./expenses')
const promoCodeRoutes = require('./promoCodes')
const tableRoutes = require('./tables')
const notificationRoutes = require('./notifications')
const heldOrderRoutes = require('./heldOrders')
const customerRoutes = require('./customers')
const stockCountRoutes = require('./stockCounts')
const paymentMethodRoutes = require('./paymentMethods')
const paymentRoutes = require('./payments')

const router = Router()

router.use('/auth', authRoutes)
router.use('/products', productRoutes)
router.use('/categories', categoryRoutes)
router.use('/sales', saleRoutes)
router.use('/users', userRoutes)
router.use('/inventory', inventoryRoutes)
router.use('/reports', reportRoutes)
router.use('/suppliers', supplierRoutes)
router.use('/audit-logs', auditRoutes)
router.use('/config', configRoutes)
router.use('/permissions', permissionRoutes)
router.use('/purchase-orders', purchaseOrderRoutes)
router.use('/expenses', expenseRoutes)
router.use('/promo-codes', promoCodeRoutes)
router.use('/tables', tableRoutes)
router.use('/notifications', notificationRoutes)
router.use('/held-orders', heldOrderRoutes)
router.use('/customers', customerRoutes)
router.use('/stock-counts', stockCountRoutes)
router.use('/payment-methods', paymentMethodRoutes)
router.use('/payments', paymentRoutes)

module.exports = router
